---
title: "Applied Biostatistics 1 Introduction"
author: "CUNY Graduate School of Public Health and Health Policy"
output: ioslides_presentation
---

<!--
Welcome to applied biostatistics one.
-->

## Applied Biostatistics I

* Introduction

<!--
This course was created using the 'ari' R package and Amazon Polly.
-->

## Course Orientation

* Features of this course
    * Multivariate Statistical Analysis
    * General issues

<!--
 In this session, I will describe the overall features of this course including
multivariate statistical analysis and then discuss some general issues thereof.
-->

## Outline

* Introduction to Multivariate Statistical Analysis
    * Multiple linear regression
    * Logistic regression

<!--
We will study multiple linear regression and logistic regression,
and some related issues. The overall schedule is, we study multiple linear
regression in the first half of this course, and logistic regression in the
second half.
-->

## Course characteristics

* Application-oriented
* Computer-oriented
* Will analyze widely used publicly-available health data (NHANES, BRFSS, HMD…)
* Will not put strong emphasis on mathematical theories (proofs, derivations)

<!--
As a course in statistics, this course is application oriented. We will focus
on how to use the statistical methods that we learn, and how to interpret
results of the statistical analysis, rather than mathematical theories
underlying those methods. We will also place emphasis on how to use software
effectively when we carry out those statistical analyses.
-->

## Required Statistical Background

* Standard deviation, variance
* Normal distribution, t-distribution
* Statistical significance, p-value, null hypothesis,
* one-sided and two-sided tests
* Confidence interval, standard error, sampling distribution
* Pearson’s correlation coefficient, simple linear regression
* No calculus or matrix algebra required
* The exponential and logistic function in the second half (very basic treatment)

<!--
You are supposed to have taken a course in introductory statistics or
biostatistics, and have general understanding of these basic statistical
concepts and tools. But you don't have to be able to remember their formulas
exactly. No background in advanced mathematics, such as calculus and matrix
algebra or linear algebra, is required. Basics of the exponential function and
logistic function that you studied in your high school algebra course, will be
used in the second half of this course.
-->

## Widely Used Software for Statistical Analysis

* User-friendly statistical software (SPSS, SAS, STATA, …)
* Programming-oriented statistical/computational software (MATLAB, R, Gauss, …)
* Programming languages (C++, Pascal, Basic, APL, Fortran, …)
* Spreadsheets including Excel

<!--
These days, computers are used heavily in statistical analysis. Computer
software used in statistical analysis may be classified into roughly four
groups. User-friendly statistical software packages such as SPSS, sass and
Stata are widely used. More technically oriented users may prefer to use
programming oriented statistical software or computational software such as R,
Matlab, and Gauss. Originally, statisticians did statistical analyses using
programming languages such as Fortran. In addition, these days, spreadsheets
are equipped with more statistical functions, so quite a few statistical
analyses can be done using a spreadsheet such as Excel, which also produces
minimal graphics. In this course, we will be exposed to three softwares, R,
sass, SPSS, which are widely used in public health research. We will
occasionally use Excel to complement sass.
-->

## Software access

R

* [R statistical software](https://cran.r-project.org/)
* [RStudio user interface](https://rstudio.com/products/rstudio/download/)

Running SAS / SPSS at home:

* Use the [CUNY Virtual Desktop](https://www.cuny.edu/about/administration/offices/cis/virtual-desktop/)
* Obtain a SAS or SPSS license from SPH
* Install SAS University Edition (SAS Studio)

<!--
By far, the easiest software to use and install is R because it is free and
open source software. The R Project and R Studio websites will allow you to
obtain the programming language and the graphical user interface, respectively.
Students looking to use sass or SPSS from home have several options.
You can use the CUNY Virtual Desktop where remote desktop software installation
is required to obtain access.  SPH should have sass and/or SPSS licenses for
student use that allow you to install the software directly onto your PC.
Lastly, sass provides sass university edition for free which requires a bit
more software installation. Currently the sass university edition is
recommended for student use because there are no delays in obtaining the
software and the installation time is shorter than the full installation of
sass.
-->

## Typical software use

1) Point-and-Click
2) Write R scripts, SAS programs, SPSS syntax

Emphasis of this course is on _2_

<!--
There are typically two ways to interface with software. One way is to have the
user look through menus and make choices from the menus and interactive
windows. The second way is to write commands and execute the operations.
Emphasis of this course is placed on writing software syntax or programs
because skill and experience translates to being able to create reproducible
analyses and workflows.
-->

